name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u amayiro2552 --password-stdin

    - name: Publish to GitHub Container Registry
      run: |
        docker tag my-image-name:latest ghcr.io/amayiro2552/ue19_labo09-10:latest
        docker push ghcr.io/amayiro2552/ue19_labo09-10:latest
