name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        IMAGE_NAME=my-image-name:latest
        docker build . --file Dockerfile --tag $IMAGE_NAME
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    - name: Publish to GitHub Container Registry
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u amayiro2552 --password-stdin
        docker tag $IMAGE_NAME ghcr.io/amayiro2552/ue19_labo09-10:latest
        docker push ghcr.io/amayiro2552/ue19_labo09-10:latest
